CREATE TABLE categories (
  id SERIAL PRIMARY KEY,
  cat_name VARCHAR(50) NOT NULL
);

INSERT into  categories (cat_name ) VALUES 
('Dasturlash'),
('Marketing'),
('Dizayin'),
('SMM'),
('Frontend'),
('3D Max'),
('Moushin'),
('UX-UI'),
('DevOps'),
('QA');

CREATE TABLE sap_categories (
  id SERIAL PRIMARY KEY,
  sap_name VARCHAR(50) NOT NULL,
  cat_ref_id INTEGER REFERENCES categories(id)
);

INSERT INTO sap_categories (sap_name, cat_ref_id) VALUES
('Python', 1),
('Java', 1),
('Javascript', 1),
('NodeJs', 1),
('Golang', 1),
('DotNet', 1),
('ReactJs', 1),
('VueJs', 1),
('NestJs', 1),
('Savdo', 2),
('Bozor', 2),
('Hamkor', 2),
('Chiqim', 2),
('Grafika', 3),
('Logo', 3),
('Illustrator', 3),
('Shrift', 3),
('Muqova', 3),
('Brend', 4),
('Blog', 4),
('Media', 4),
('Teg', 5),
('Figma', 5),
('Bootstrap', 5),
('Position', 5),
('Interyer', 6),
('Tashqi uy', 6),
('Office', 6),
('Animatsiya', 7),
('Illustrator', 7),
('Focus', 7);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL unique,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL
);

insert into users (username, email, password) values
('Islom', 'islom@shinystat.com', '2222'),
('Sarvar', 'sarvar@ning.com', '1111'),
('Jamshid', 'jamshid@last.fm', '0000'),
('Alisher', 'alisher@sciencedaily.com', '3322'),
('Anvar', 'anvar@over-blog.com', '0022'),
('Elbek', 'elbek@businesswire.com', '1122'),
('Shahboz', 'shahboz@thetimes.co.uk', '3333'),
('Lobar', 'obar@unc.edu', '4444'),
('Ravshan', 'avshan@miibeian.gov.cn', '4422'),
('Po''lat', 'polat@amazon.com', '3344'),
('Lochin', 'lochin@ucsd.edu', '2244'),
('Botir', 'botir@amazon.de', '5555'),
('Elshod', 'eelshod@aboutads.info', '5522'),
('Tolib', 'tolib@deliciousdays.com', '3344'),
('Davron', 'davron@admin.ch', '1144');


CREATE TABLE videos (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  title VARCHAR(100) NOT NULL,
  sap_category_id INTEGER REFERENCES sap_categories(id),
  link VARCHAR(200) NOT NULL
);

insert into videos (user_id, title, sap_category_id, link) values 
(7, 'Realcube', 24, 'https://robohash.org/quaeratetin.png'),
(4, 'Tanoodle', 26, 'https://robohash.org/etrerumqui.png'),
(2, 'Shufflester', 12, 'https://robohash.org/exercitationemquosquasi.png'),
(2, 'Eamia', 25, 'https://robohash.org/iustositsoluta.png'),
(10, 'Agivu', 23, 'https://robohash.org/reiciendisundefugiat.png'),
(12, 'Quinu', 11, 'https://robohash.org/fugaquiquas.png'),
(5, 'Quimm', 24, 'https://robohash.org/estvelexpedita.png'),
(6, 'Edgeblab', 1, 'https://robohash.org/faceresequisapiente.png'),
(6, 'Gabtune', 30, 'https://robohash.org/perspiciatisearumut.png'),
(10, 'Eazzy', 16, 'https://robohash.org/liberoipsumexpedita.png'),
(3, 'Eimbee', 10, 'https://robohash.org/quamducimussed.png'),
(12, 'Mita', 27, 'https://robohash.org/doloribusutnihil.png'),
(8, 'Yabox', 5, 'https://robohash.org/nullatemporaet.png'),
(15, 'Gabvine', 27, 'https://robohash.org/mollitiavoluptatesfuga.png'),
(12, 'Buzzbean', 29, 'https://robohash.org/adipisciporrooptio.png'),
(7, 'Skivee', 25, 'https://robohash.org/odiodoloribusconsequatur.png'),
(6, 'Tagfeed', 23, 'https://robohash.org/nihilvoluptaslibero.png'),
(10, 'Latz', 17, 'https://robohash.org/illumistequi.png'),
(9, 'Skipfire', 15, 'https://robohash.org/providentestveniam.png'),
(9, 'Blogtags', 12, 'https://robohash.org/odionesciuntrepellat.png'),
(9, 'Pixonyx', 23, 'https://robohash.org/aliquidestet.png'),
(12, 'Jabbercube', 5, 'https://robohash.org/quirerumducimus.png'),
(13, 'Quinu', 25, 'https://robohash.org/quasiomnisin.png'),
(9, 'Flipstorm', 22, 'https://robohash.org/impeditomnisearum.png'),
(11, 'Dynazzy', 19, 'https://robohash.org/ideumut.png'),
(11, 'Miboo', 25, 'https://robohash.org/atsitiste.png'),
(11, 'Meejo', 24, 'https://robohash.org/architectoquaedoloremque.png'),
(13, 'Wordpedia', 4, 'https://robohash.org/quasiquaeratfacilis.png'),
(1, 'Voonix', 26, 'https://robohash.org/facilismollitiaaut.png'),
(2, 'Abatz', 20, 'https://robohash.org/praesentiumcupiditatesed.png'),
(5, 'Gevee', 20, 'https://robohash.org/natusincidunta.png'),
(4, 'Quatz', 9, 'https://robohash.org/porronullanemo.png'),
(15, 'Kimia', 3, 'https://robohash.org/impediteiusipsum.png'),
(3, 'Dabshots', 3, 'https://robohash.org/etasperioreseius.png'),
(6, 'Ainyx', 5, 'https://robohash.org/dolorumeaquenon.png'),
(14, 'Zoomdog', 10, 'https://robohash.org/velitminusratione.png'),
(9, 'Wordpedia', 10, 'https://robohash.org/doloresdelectusab.png'),
(1, 'Vinder', 18, 'https://robohash.org/doloremestnon.png'),
(4, 'Oyonder', 3, 'https://robohash.org/quaerattemporacommodi.png'),
(2, 'Brainverse', 11, 'https://robohash.org/doloresducimusqui.png'),
(10, 'Flashpoint', 16, 'https://robohash.org/maximeofficiatemporibus.png'),
(13, 'Oyoba', 21, 'https://robohash.org/autsaepeofficiis.png'),
(7, 'Skiba', 3, 'https://robohash.org/etoptiomaiores.png'),
(7, 'Meevee', 12, 'https://robohash.org/utsitexercitationem.png'),
(1, 'Yabox', 11, 'https://robohash.org/facereomnisasperiores.png'),
(1, 'Trilith', 12, 'https://robohash.org/atvoluptatemiure.png'),
(15, 'Vinder', 9, 'https://robohash.org/nonodioodit.png'),
(4, 'Jayo', 15, 'https://robohash.org/rerummollitiarepellendus.png'),
(14, 'Miboo', 12, 'https://robohash.org/autetdicta.png'),
(4, 'Leenti', 17, 'https://robohash.org/perferendismaximequi.png'),
(2, 'Dabfeed', 24, 'https://robohash.org/erroraliquamipsum.png'),
(6, 'Voonte', 28, 'https://robohash.org/etsuscipitperferendis.png'),
(15, 'Gabcube', 30, 'https://robohash.org/temporarerumanimi.png'),
(6, 'Jatri', 12, 'https://robohash.org/sintquosrerum.png'),
(13, 'Voonder', 26, 'https://robohash.org/voluptasperspiciatisullam.png'),
(6, 'Yoveo', 2, 'https://robohash.org/quodinventoresed.png'),
(3, 'Jabberstorm', 27, 'https://robohash.org/rerumnatuscorporis.png'),
(5, 'Shufflester', 24, 'https://robohash.org/possimussitautem.png'),
(15, 'Tambee', 9, 'https://robohash.org/quaeratsintaut.png'),
(3, 'Trunyx', 8, 'https://robohash.org/evenietnequequis.png'),
(6, 'Dabjam', 21, 'https://robohash.org/inventoreaspernaturtempore.png'),
(9, 'Fivechat', 19, 'https://robohash.org/quossitcupiditate.png'),
(6, 'Brightdog', 18, 'https://robohash.org/possimusdoloribustempora.png'),
(7, 'Zoomcast', 28, 'https://robohash.org/nequevoluptatemdolorum.png'),
(4, 'Flashspan', 20, 'https://robohash.org/totammodimolestiae.png'),
(10, 'Mita', 19, 'https://robohash.org/etconsequaturtempora.png'),
(6, 'Minyx', 12, 'https://robohash.org/atquevitaeaccusantium.png'),
(14, 'Gigazoom', 7, 'https://robohash.org/possimusquiexpedita.png'),
(5, 'Fliptune', 22, 'https://robohash.org/rationeporroharum.png'),
(5, 'Quaxo', 23, 'https://robohash.org/explicaboautemlaboriosam.png'),
(12, 'Kanoodle', 28, 'https://robohash.org/necessitatibussaepequia.png'),
(5, 'Eire', 3, 'https://robohash.org/accusamusquiafuga.png'),
(8, 'Gabtype', 1, 'https://robohash.org/voluptatumcumqueut.png'),
(15, 'Avavee', 19, 'https://robohash.org/corruptieosconsequatur.png'),
(11, 'Flashspan', 12, 'https://robohash.org/voluptatumperspiciatisarchitecto.png'),
(3, 'Kimia', 22, 'https://robohash.org/optioinrerum.png'),
(14, 'Riffwire', 18, 'https://robohash.org/voluptatemodiorerum.png'),
(14, 'Flipstorm', 29, 'https://robohash.org/hicquasdoloremque.png'),
(8, 'Jaxworks', 2, 'https://robohash.org/doloreoccaecatiet.png'),
(8, 'Shufflester', 26, 'https://robohash.org/ipsamsintut.png'),
(3, 'Skaboo', 7, 'https://robohash.org/voluptatemestqui.png'),
(10, 'Jabbersphere', 21, 'https://robohash.org/accusamusnatusmaxime.png'),
(5, 'Gabspot', 15, 'https://robohash.org/omnisveritatisvel.png'),
(8, 'Kazu', 18, 'https://robohash.org/sedaperiama.png'),
(6, 'Vidoo', 9, 'https://robohash.org/reprehenderiteiusdeserunt.png'),
(4, 'Omba', 9, 'https://robohash.org/estitaquequi.png'),
(5, 'Eidel', 17, 'https://robohash.org/exercitationemoccaecatisunt.png'),
(4, 'Avamm', 24, 'https://robohash.org/etetesse.png'),
(3, 'Jaxbean', 13, 'https://robohash.org/suntsintsed.png'),
(13, 'Mydo', 20, 'https://robohash.org/eumreiciendisconsectetur.png'),
(6, 'Tanoodle', 21, 'https://robohash.org/teneturnonnon.png'),
(1, 'Photojam', 22, 'https://robohash.org/autrema.png'),
(11, 'Ntag', 11, 'https://robohash.org/consequaturutrepellendus.png'),
(5, 'Yodel', 7, 'https://robohash.org/perspiciatisasit.png'),
(14, 'Quinu', 9, 'https://robohash.org/doloribusomnisearum.png'),
(3, 'Skipfire', 15, 'https://robohash.org/evenietcumcorporis.png'),
(1, 'Tazz', 22, 'https://robohash.org/providentoditearum.png'),
(8, 'Tazzy', 29, 'https://robohash.org/etlaborumvel.png'),
(1, 'Tagchat', 1, 'https://robohash.org/verononet.png'),
(7, 'Fadeo', 7, 'https://robohash.org/aliquamquibusdamnihil.png');

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  video_id INTEGER REFERENCES videos(id),
  content TEXT NOT NULL
);

INSERT INTO comments ( user_id, video_id, content) VALUES
(5, 5, 'Serous detachment of retinal pigment epithelium'),
(6, 15, 'Plantar wart'),
(14, 5, 'Chronic or unspecified gastrojejunal ulcer with perforation, without mention of obstruction'),
(13, 8, 'Gonococcal endometritis (acute)'),
(6, 15, 'Hereditary disease in family possibly affecting fetus, affecting management of mother, antepartum condition or complication'),
(3, 11, 'Toxic erythema'),
(6, 2, 'Herpes zoster with unspecified complication'),
(10, 13, 'Behavioral insomnia of childhood'),
(15, 4, 'Juvenile osteochondrosis of spine'),
(8, 19, 'Postsurgical hypoinsulinemia'),
(11, 3, 'Accidental poisoning by other specified solid or liquid substances'),
(9, 19, 'Lymphosarcoma, intrathoracic lymph nodes'),
(8, 2, 'Burn of vagina and uterus'),
(4, 15, 'Ehrlichiosis chafeensis [E. chafeensis]'),
(14, 7, 'Thalassemia minor'),
(1, 14, 'Nursemaid''s elbow'),
(6, 18, 'Fetal growth retardation, unspecified, 2,000-2,499 grams'),
(11, 1, 'Other specified behavioral problem'),
(10, 2, 'Injury to cervical sympathetic nerve, excluding shoulder and pelvic girdles'),
(3, 8, 'Bipolar I disorder, most recent episode (or current) unspecified'),
(2, 10, 'Foreign object left in body during surgical operation'),
(2, 13, 'Closed fracture of olecranon process of ulna'),
(1, 15, 'Acute venous embolism and thrombosis of upper extremity, unspecified'),
(2, 2, 'Infantile cerebral palsy, unspecified'),
(7, 11, 'Hematemesis'),
(14, 9, 'Accidental mechanical suffocation by other specified means'),
(4, 8, 'Congenital aphakia'),
(15, 5, 'Respiratory syncytial virus (RSV)'),
(13, 12, 'Poisoning by unspecified central nervous system stimulant'),
(12, 6, 'Systemic inflammatory response syndrome, unspecified'),
(2, 2, 'Malignant neoplasm of dorsal surface of tongue'),
(6, 18, 'Illegally induced abortion, without mention of complication, incomplete'),
(12, 7, 'Noise-induced hearing loss'),
(7, 14, 'Primary tuberculous infection, unspecified, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically'),
(9, 17, 'Failed attempted abortion complicated by metabolic disorder'),
(5, 3, 'Nonspecific (abnormal) findings on radiological and other examination of biliary tract'),
(10, 6, 'Dementia in conditions classified elsewhere with behavioral disturbance'),
(11, 16, 'Other specified visual disturbances'),
(13, 12, 'Duodenal ulcer, unspecified as acute or chronic, without hemorrhage or perforation, without mention of obstruction'),
(10, 3, 'Choroidal rupture'),
(7, 15, 'Acute rheumatic pericarditis'),
(6, 9, 'Acute diastolic heart failure'),
(14, 6, 'Screening for rheumatoid arthritis'),
(8, 20, 'Uterine size date discrepancy, postpartum condition or complication'),
(13, 12, 'Vascular abnormalities of conjunctiva'),
(6, 11, 'Blisters, epidermal loss [second degree] of breast'),
(6, 2, 'Injury to axillary vessel(s), unspecified'),
(1, 2, 'Disturbances of sulphur-bearing amino-acid metabolism'),
(12, 16, 'Injury to lumbosacral plexus'),
(8, 15, 'Toxic effect of freon'),
(1, 8, 'Mobitz (type) II atrioventricular block'),
(11, 4, 'Lateral dislocation of tibia, proximal end, open'),
(10, 11, 'Physical restraints status'),
(5, 8, 'Newborn affected by previous surgical procedure on mother not associated with pregnancy'),
(10, 19, 'Encounter for emergency contraceptive counseling and prescription'),
(8, 14, 'Other specified cardiac device in situ'),
(5, 18, 'Benign neoplasm of nasal cavities, middle ear, and accessory sinuses'),
(14, 18, 'Malignant neoplasm of waldeyer''s ring'),
(12, 6, 'Legally induced abortion, complicated by renal failure, incomplete'),
(4, 2, 'Attention to other specified artificial opening');
